# Generated by Django 5.1.1 on 2024-10-03 13:35

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clientinfo', '0002_initial'),
        ('inventory', '0003_initial'),
        ('produits', '0001_initial'),
        ('reglements', '0002_initial'),
        ('tiers', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentesCustomPermission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Custom Permission',
                'verbose_name_plural': 'Custom Permissions',
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField(default=datetime.datetime.now)),
                ('date_reglement', models.DateField(default=datetime.datetime.now)),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('regle', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bonS_commande', to='tiers.client')),
                ('echeance_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglements.echeancereglement')),
                ('mode_reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_reglements_type', to='reglements.modereglement')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commande', to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='BonDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bonS_devis', to='tiers.client')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_devis', to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('num_cheque_reglement', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('Remise', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('agenceLivraison', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('fraisLivraison', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fraisLivraisonexterne', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note', models.TextField(default='')),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('modifiable', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=True)),
                ('livre', models.BooleanField(default=False)),
                ('typebl', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reference_pc', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name_pc', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('banque_Reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_reglements_bonL', to='tiers.banque')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bonS', to='tiers.client')),
                ('echeance_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonL_reglements_echeance', to='reglements.echeancereglement')),
                ('entrepot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bons', to='inventory.entrepot')),
                ('mode_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonL_reglements_type', to='reglements.modereglement')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonL_store', to='clientinfo.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons', to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='BonGarantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('tps_ecoule', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.client')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_garantie', to='user.customuser')),
                ('bonLivraisonAssocie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bon_garantie', to='ventes.bonsortie')),
            ],
        ),
        migrations.CreateModel(
            name='AvoirVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeAvoir', models.CharField(max_length=200)),
                ('dateEmission', models.DateField(default=datetime.datetime.now)),
                ('motif', models.CharField(default='', max_length=200)),
                ('montant', models.CharField(default='', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoirs_client', to='tiers.client')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store')),
                ('BonSortieAssocie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoirs_bonsortie', to='ventes.bonsortie')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationBl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateConfirmation', models.DateTimeField()),
                ('dateLivraisonPrevu', models.DateField()),
                ('fichier_confirmation', models.FileField(upload_to='media/document')),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confrimation_bon', to='ventes.bonsortie')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('BonSNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_sortie_transfert', to='ventes.bonsortie')),
                ('BonTransfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_transfert', to='inventory.bontransfert')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeFacture', models.CharField(max_length=200, unique=True)),
                ('date_facture', models.DateField()),
                ('date_reglement', models.DateField(default=datetime.datetime.now)),
                ('num_cheque_reglement', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('Remise', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('etat_reglement', models.CharField(choices=[('en Attente', 'en Attente'), ('Règlement Reçu', 'Règlement Reçu'), ('Expédié', 'Expédié'), ('Facture', 'Facture'), ('Facture Comptabilisé', 'Facture Comptabilisé')], max_length=30)),
                ('shippingCost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('totalPrice', models.IntegerField(default=0)),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('regle', models.BooleanField(default=False)),
                ('BonS', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonS_facture', to='ventes.bonsortie')),
                ('banque_Reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_reglements', to='tiers.banque')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_facture', to='tiers.client')),
                ('echeance_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_reglements_echeance', to='reglements.echeancereglement')),
                ('mode_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_reglements_type', to='reglements.modereglement')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_commande', to='ventes.boncommande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commande', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_devis', to='ventes.bondevis')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_devis', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonGarantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('livre', models.BooleanField(default=False)),
                ('NumeroSeries', models.TextField(default='')),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_garantie', to='ventes.bongarantie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_garantie', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.TextField(default='')),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_sorties', to='ventes.bonsortie')),
                ('entrepot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesproduit_bons_sortie', to='inventory.entrepot')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_sortie', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unitprice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('totalprice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('FactureNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_facture', to='ventes.facture')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='validationBl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_validation', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('codeBl', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('montantBl', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('solde_note', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('client_name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_validation', to='user.customuser')),
            ],
        ),
    ]
