# Generated by Django 4.2.5 on 2024-10-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientinfo', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientinfoCustomPermission',
        ),
    ]
