# Generated by Django 5.1.1 on 2024-10-03 13:35

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clientinfo', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitsCustomPermission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Custom Permission',
                'verbose_name_plural': 'Custom Permissions',
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Variantes_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_lib', models.CharField(max_length=100)),
                ('values_list', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.BooleanField(default=True)),
                ('kitcomponents', models.TextField(default='')),
                ('Libellé', models.CharField(max_length=100)),
                ('categoryDesc', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('status', models.BooleanField(default=True)),
                ('pc_component', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('MotherCategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='produits.category')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence interne pour ce produit', max_length=120, verbose_name='Référence du produit')),
                ('name', models.CharField(help_text='La désignation du produit', max_length=200, null=True, verbose_name='Désignation')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_pc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_kit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva_douan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('initial_qte', models.IntegerField()),
                ('QuantityPerCarton', models.IntegerField(default=0)),
                ('TotalQte', models.IntegerField(default=0)),
                ('reforme', models.BooleanField(default=False)),
                ('fournisseur', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='produits.category')),
                ('parent_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myvariants', to='produits.product')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='NumSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numseries', models.CharField(max_length=250)),
                ('used', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myserialnumbers', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAchatProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_qctuelle', models.IntegerField(default=0)),
                ('prix_achat_actuelle', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qty_achete', models.IntegerField(default=0)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_achat_calcule', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dateAchat', models.DateField()),
                ('produit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monHIstoriqueAchat', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='historique_prix_achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('prix_achat_original', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_achat_newer', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('product', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='codeEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('produit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moncodeEAN', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_pc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_kit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_carton', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('product', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='produits.product')),
                ('type_client', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='clientinfo.typeclient')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_set', to='produits.product')),
                ('variant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_set', to='produits.variantes_product')),
            ],
        ),
        migrations.CreateModel(
            name='variantsPrixClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_pc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_kit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_carton', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('produit', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='produit_var', to='produits.product')),
                ('type_client', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='prix_var', to='clientinfo.typeclient')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeArchive', models.CharField(max_length=255)),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entrepot')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='ListProductVerificationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reference', models.CharField(max_length=255)),
                ('realQuantity', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('verification_result', models.CharField(max_length=255)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_verification', to='produits.verificationarchive')),
            ],
        ),
    ]
