# Generated by Django 5.1.1 on 2024-10-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientinfo', '0002_initial'),
        ('comptoire', '0001_initial'),
        ('inventory', '0002_initial'),
        ('produits', '0001_initial'),
        ('reglements', '0001_initial'),
        ('tiers', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationcaisse',
            name='utilisateur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_affectation', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='caisse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesbons_comptoir', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_comptoir_store', to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_comptoire', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='caisse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesbons_rectification', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_rectif_store', to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_rectification', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonretourcomptoir',
            name='bon_comptoir_associe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_retour_compt', to='comptoire.boncomptoire'),
        ),
        migrations.AddField(
            model_name='bonretourcomptoir',
            name='bon_rectification_associe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_retour_compt', to='comptoire.bonrectification'),
        ),
        migrations.AddField(
            model_name='bonretourcomptoir',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsretour_compt', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonretourcomptoir',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retourcomptoire', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='cloture',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='cloture',
            name='utilisateur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_points_ventes', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='mode_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointVentes', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='pointVente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptoire.pointvente'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='pointVente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptoire.pointvente'),
        ),
        migrations.AddField(
            model_name='affectationcaisse',
            name='emplacement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_affectation', to='comptoire.pointvente'),
        ),
        migrations.AddField(
            model_name='produitsenboncomptoir',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_comptoir', to='comptoire.boncomptoire'),
        ),
        migrations.AddField(
            model_name='produitsenboncomptoir',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_boncomp', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='produitsenboncomptoir',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_comptoir', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonrectif',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_rectification', to='comptoire.bonrectification'),
        ),
        migrations.AddField(
            model_name='produitsenbonrectif',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_rectification', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='produitsenbonrectif',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_rectif', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonretourcomptoir',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_retourcomptoir', to='comptoire.bonretourcomptoir'),
        ),
        migrations.AddField(
            model_name='produitsenbonretourcomptoir',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retourcomptoir', to='produits.product'),
        ),
        migrations.AddField(
            model_name='verssement',
            name='bon_comptoir_associe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verssements', to='comptoire.boncomptoire'),
        ),
        migrations.AddField(
            model_name='verssement',
            name='bon_rectification_associe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verssements', to='comptoire.bonrectification'),
        ),
        migrations.AddField(
            model_name='verssement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='verssement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
    ]
