# Generated by Django 5.1.1 on 2024-10-03 13:35

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clientinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EcheanceReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueMontantRecuperer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('num_cheque', models.CharField(blank=True, default='', max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='montantCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='mouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motif', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeReglement', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('type_reglement', models.CharField(choices=[('paiement', 'paiement'), ('remboursement', 'remboursement')], max_length=100)),
                ('collected', models.BooleanField(default=False)),
                ('dateReglement', models.DateField()),
                ('num_cheque', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pj')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReglementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeReglement', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('type_reglement', models.CharField(choices=[('paiement', 'paiement'), ('remboursement', 'remboursement')], max_length=100)),
                ('collected', models.BooleanField(default=False)),
                ('dateReglement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReglementsCustomPermission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Custom Permission',
                'verbose_name_plural': 'Custom Permissions',
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('salaire', 'Salaire'), ('loyer', 'Loyer'), ('divers', 'Divers')], max_length=20)),
                ('nom_salarie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fonction_salarie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adresse_salarie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tlfn_salarie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('numero_local', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adresse_local', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClotureReglements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField()),
                ('collected', models.BooleanField(default=False)),
                ('montant_collected', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('caisse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clotures_reg', to='clientinfo.compteentreprise')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store')),
            ],
        ),
    ]
