# Generated by Django 5.1.1 on 2024-10-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0003_initial'),
        ('clientinfo', '0002_initial'),
        ('reglements', '0002_initial'),
        ('tiers', '0002_initial'),
        ('user', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='BonS',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonS_reglements', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='CompteEntreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reglements', to='clientinfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reglements', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='facture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_reglements', to='ventes.facture'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_type', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='montantSource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep_reglements', to='reglements.historiquemontantrecuperer'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='BonA',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonAchats_reglements', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='CompteEntreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs_reglements', to='clientinfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='facture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factureAchats_reglements', to='achats.factureachat'),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_reglements', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_typefournisseur', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='typedepense',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='depense',
            name='type_depense',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_depenses', to='reglements.typedepense'),
        ),
    ]
