# Generated by Django 5.1.1 on 2024-10-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientinfo', '0002_initial'),
        ('comptoire', '0002_initial'),
        ('inventory', '0002_initial'),
        ('tiers', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonechange',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_echange', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs_bons_entry', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_entry', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonLComptoir',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MesbonmaintenanceComptoir', to='comptoire.bonretourcomptoir'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_maintenance', to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_maintenance', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_reforme', to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reforme', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reintegration', to='user.customuser'),
        ),
    ]
