# Generated by Django 5.1.1 on 2024-10-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientinfo', '0002_initial'),
        ('tiers', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_clients', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='Agence',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_banque_client', to='tiers.agence'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='Banque',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_banque_client', to='tiers.banque'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_bancaire_client', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_store', to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_bancaire_client', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='prospectionclient',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_prospection', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='region',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_regions', to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='tentatives',
            name='propspection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_tentative', to='tiers.prospectionclient'),
        ),
        migrations.AddField(
            model_name='tentatives',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_tentatives', to='user.customuser'),
        ),
    ]
