# Generated by Django 5.1.1 on 2024-10-03 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvoirAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeAvoir', models.CharField(max_length=200)),
                ('dateEmission', models.DateField(default=datetime.datetime.now)),
                ('motif', models.CharField(default='', max_length=200)),
                ('montant', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BonAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BonCommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('destinataire', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Tva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DDtax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ttctax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tauxChange', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='BonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('chauffeur', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('immatriculation', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmission', models.DateField()),
                ('motifCredit', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('totalUsd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalDZ', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tauxChange', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='DossierAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDossier', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateDossier', models.DateField()),
                ('facture', models.FileField(upload_to='media/document')),
                ('monnaie', models.CharField(default='', max_length=255)),
                ('MontantEtrange', models.DecimalField(decimal_places=2, default=0, max_digits=35)),
                ('TypePaiement', models.CharField(default='', max_length=255)),
                ('AvisDebit', models.FileField(upload_to='media/document')),
                ('datePaiement', models.DateField()),
                ('MontantDZD', models.DecimalField(decimal_places=2, default=0, max_digits=35)),
                ('DateValeur', models.FileField(upload_to='media/document')),
                ('DateValeurdate', models.DateField(default=datetime.datetime.now)),
                ('DateMontant', models.DateField(default=datetime.datetime.now)),
                ('TauxChange', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_bon', models.CharField(default='', max_length=200, verbose_name='id Bon')),
                ('Port_debarquement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('port_embarquement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nombre_colis', models.IntegerField(default=0)),
                ('etat', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_depart', models.DateField()),
                ('date_arrive', models.DateField()),
                ('date_remise_transitaire', models.DateField()),
                ('date_domiciliation', models.DateField()),
                ('date_conaissement', models.DateField()),
                ('nbr_jours_port', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FactureAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeFacture', models.CharField(max_length=200, unique=True)),
                ('date_facture', models.DateField()),
                ('Remise', models.DecimalField(decimal_places=2, max_digits=15)),
                ('etat_reglement', models.CharField(max_length=250)),
                ('shippingCost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('totalPrice', models.IntegerField(default=0)),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('regle', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixUnitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonCommandesAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixUnitaireDZ', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prixUnitairUSD', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('totalPriceDZ', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalPriceUSD', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transportPercent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transportPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('chargesApproximatively', models.DecimalField(decimal_places=2, max_digits=15)),
                ('chargesPercent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxesUnitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxesTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Totalcharges', models.DecimalField(decimal_places=2, max_digits=15)),
                ('anda', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DroitRealisation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixUnitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puUsdAchat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('puDaAchat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantityAchete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnFactureAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unitprice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('totalprice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProjet', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Marque', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('dateProjet', models.DateField()),
                ('designation', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cnn', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('FichierProjet', models.FileField(upload_to='media/document')),
            ],
        ),
    ]
