# Generated by Django 5.1.1 on 2024-10-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('clientinfo', '0002_initial'),
        ('inventory', '0001_initial'),
        ('reglements', '0001_initial'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoirachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avoirs_fournisseur', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='avoirachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='echeance_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonachatt_reglements_echeance', to='reglements.echeancereglement'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonachat', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_achat', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='mode_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonachat_reglements_type', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='monnaie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monnaie_bonachat', to='clientinfo.valeurdevise'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_achat', to='clientinfo.store'),
        ),
    ]
