# Generated by Django 5.1.1 on 2024-10-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0002_initial'),
        ('clientinfo', '0002_initial'),
        ('inventory', '0002_initial'),
        ('produits', '0001_initial'),
        ('reglements', '0001_initial'),
        ('tiers', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_achat', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='avoirachat',
            name='BonSortieAssocie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoirs_bonachat', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='echeance_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achat_reglements_echeance', to='reglements.echeancereglement'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_commandeachat', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='livraison',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achat_reglements_type', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='monnaie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.valeurdevise'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_commandesachat', to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commandesachats', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='BonAchat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsachat_bonreception', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonreception', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='unite_monitaire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitemonitaire_bonreception', to='clientinfo.valeurdevise'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reception', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='BonAchat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bon_achats_credit', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_creditd', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='BonCommande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_achat_commande', to='achats.boncommandeachat'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='banque_Reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_dossierachat', to='tiers.banque'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_dossier_achat', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_dossier_achat', to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_dossier_achat', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='banque_domiciliation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedition_banque', to='tiers.banque'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='bon_commande',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedition_commandes', to='achats.boncommandeachat'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_expedition', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='expedition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedition_bonreception', to='achats.expedition'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='BonAchat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsachat_facture', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='echeance_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factureachat_reglements_echeance', to='reglements.echeancereglement'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_facture_achat', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='livraison',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factureachat_reglements_type', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='monnaie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.valeurdevise'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_factureachat', to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_facture_achat', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='produitsenbonachat',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_achat', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='produitsenbonachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_achat', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_commandeachat', to='achats.boncommandeachat'),
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commandesachat', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonreception',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_reception', to='achats.bonreception'),
        ),
        migrations.AddField(
            model_name='produitsenbonreception',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reception', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsencreditnote',
            name='Credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_creditNote', to='achats.creditnote'),
        ),
        migrations.AddField(
            model_name='produitsencreditnote',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_creditNote', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenfactureachat',
            name='FactureNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_factureachats', to='achats.factureachat'),
        ),
        migrations.AddField(
            model_name='produitsenfactureachat',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_achat', to='produits.product'),
        ),
        migrations.AddField(
            model_name='projetcredit',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientinfo.store'),
        ),
        migrations.AddField(
            model_name='projetcredit',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_projets', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='Projet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bon_achats_credit', to='achats.projetcredit'),
        ),
    ]
